# Generated by Django 3.1.7 on 2021-03-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frm', models.CharField(max_length=100)),
            ],
        ),
    ]
